"CREATE TRIGGER employeetrr
AFTER INSERT ON EDW_RESTORE_TABLES.EMPLOYEE
REFERENCING NEW_TABLE AS employeenew
FOR EACH STATEMENT
( INSERT INTO EDW_RESTORE_TABLES.EMPLOYEE_LOG(Employeeid,Employeename,Salary) SELECT Employeeid,Employeename,Salary FROM employeenew;)"